package analysis

type KeywordInfo struct {
	Name        string
	Detail      string
	InsertText  string
}

var BSLKeywords = []KeywordInfo{
	{Name: "Если", Detail: "If", InsertText: "Если "},
	{Name: "Тогда", Detail: "Then"},
	{Name: "ИначеЕсли", Detail: "ElseIf", InsertText: "ИначеЕсли "},
	{Name: "Иначе", Detail: "Else"},
	{Name: "КонецЕсли", Detail: "EndIf"},
	{Name: "Пока", Detail: "While", InsertText: "Пока "},
	{Name: "Цикл", Detail: "Do"},
	{Name: "КонецЦикла", Detail: "EndDo"},
	{Name: "Для", Detail: "For", InsertText: "Для "},
	{Name: "По", Detail: "To"},
	{Name: "Каждого", Detail: "Each", InsertText: "Каждого "},
	{Name: "Из", Detail: "In"},
	{Name: "Попытка", Detail: "Try"},
	{Name: "Исключение", Detail: "Except"},
	{Name: "КонецПопытки", Detail: "EndTry"},
	{Name: "Процедура", Detail: "Procedure", InsertText: "Процедура "},
	{Name: "Функция", Detail: "Function", InsertText: "Функция "},
	{Name: "КонецПроцедуры", Detail: "EndProcedure"},
	{Name: "КонецФункции", Detail: "EndFunction"},
	{Name: "Перем", Detail: "Var", InsertText: "Перем "},
	{Name: "Возврат", Detail: "Return", InsertText: "Возврат "},
	{Name: "ВызватьИсключение", Detail: "Raise", InsertText: "ВызватьИсключение "},
	{Name: "Продолжить", Detail: "Continue"},
	{Name: "Прервать", Detail: "Break"},
	{Name: "Перейти", Detail: "Goto", InsertText: "Перейти "},
	{Name: "Экспорт", Detail: "Export"},
	{Name: "Знач", Detail: "ByVal"},
	{Name: "Новый", Detail: "New", InsertText: "Новый "},
	{Name: "Истина", Detail: "True"},
	{Name: "Ложь", Detail: "False"},
	{Name: "Неопределено", Detail: "Undefined"},
	{Name: "Null", Detail: "Null"},
	{Name: "Не", Detail: "Not", InsertText: "Не "},
	{Name: "И", Detail: "And"},
	{Name: "Или", Detail: "Or"},
}

var BSLGlobalMethods = []KeywordInfo{
	{Name: "Сообщить", Detail: "Сообщить(Значение)", InsertText: "Сообщить()"},
	{Name: "Предупреждение", Detail: "Предупреждение(Текст)"},
	{Name: "Вопрос", Detail: "Вопрос(Текст)"},
	{Name: "Вычислить", Detail: "Вычислить(Выражение)"},
	{Name: "Строка", Detail: "Строка(Значение)"},
	{Name: "Число", Detail: "Число(Значение)"},
	{Name: "Дата", Detail: "Дата(Значение)"},
	{Name: "Булево", Detail: "Булево(Значение)"},
	{Name: "Тип", Detail: "Тип(Значение)"},
	{Name: "ЗначениеВСтрокуВнутр", Detail: "ЗначениеВСтрокуВнутр(Значение)"},
	{Name: "СтрокаВЗначениеВнутр", Detail: "СтрокаВЗначениеВнутр(Строка)"},
	{Name: "СокрЛП", Detail: "СокрЛП(Значение)"},
	{Name: "СокрЛ", Detail: "СокрЛ(Значение)"},
	{Name: "СокрП", Detail: "СокрП(Значение)"},
	{Name: "Лев", Detail: "Лев(Строка, Длина)"},
	{Name: "Прав", Detail: "Прав(Строка, Длина)"},
	{Name: "Сред", Detail: "Сред(Строка, Начало, Длина)"},
	{Name: "СтрДлина", Detail: "СтрДлина(Строка)"},
	{Name: "Найти", Detail: "Найти(Строка, Подстрока)"},
	{Name: "ПустаяСтрока", Detail: "ПустаяСтрока(Значение)"},
	{Name: "СтрЗаменить", Detail: "СтрЗаменить(Строка, Поиск, Замена)"},
	{Name: "СтрЧислоВхождений", Detail: "СтрЧислоВхождений(Строка, Подстрока)"},
	{Name: "СтрНачинаетсяС", Detail: "СтрНачинаетсяС(Строка, Начало)"},
	{Name: "СтрОканчиваетсяНа", Detail: "СтрОканчиваетсяНа(Строка, Окончание)"},
	{Name: "СтрРазделить", Detail: "СтрРазделить(Строка, Разделитель)"},
	{Name: "СтрСоединить", Detail: "СтрСоединить(Массив, Разделитель)"},
	{Name: "ВРег", Detail: "ВРег(Строка)"},
	{Name: "НРег", Detail: "НРег(Строка)"},
	{Name: "ТРег", Detail: "ТРег(Строка)"},
	{Name: "Символ", Detail: "Символ(Код)"},
	{Name: "КодСимвола", Detail: "КодСимвола(Строка)"},
	{Name: "ПолучитьИмяФайла", Detail: "ПолучитьИмяФайла(Строка)"},
	{Name: "ОбщегоНазначения", Detail: "ОбщегоНазначения.КлиентСервер"},
}
